const TEAM_NAMES = {
  ALG: 'Algeria',
  ARG: 'Argentina',
  AUS: 'Australia',
  AUT: 'Austria',
  BEL: 'Belgium',
  BIH: 'Bosnia & Herzegovina',
  BRA: 'Brazil',
  CAN: 'Canada',
  CIV: 'Ivory Coast',
  COD: 'DR Congo',
  COL: 'Colombia',
  CPV: 'Cape Verde',
  CRO: 'Croatia',
  CUW: 'Curaçao',
  CZE: 'Czech Republic',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  ENG: 'England',
  ESP: 'Spain',
  FRA: 'France',
  GER: 'Germany',
  GHA: 'Ghana',
  HAI: 'Haiti',
  IRN: 'Iran',
  IRQ: 'Iraq',
  JOR: 'Jordan',
  JPN: 'Japan',
  KOR: 'South Korea',
  KSA: 'Saudi Arabia',
  MAR: 'Morocco',
  MEX: 'Mexico',
  NED: 'Netherlands',
  NOR: 'Norway',
  NZL: 'New Zealand',
  PAN: 'Panama',
  PAR: 'Paraguay',
  POR: 'Portugal',
  QAT: 'Qatar',
  RSA: 'South Africa',
  SCO: 'Scotland',
  SEN: 'Senegal',
  SUI: 'Switzerland',
  SWE: 'Sweden',
  TUN: 'Tunisia',
  TUR: 'Türkiye',
  URU: 'Uruguay',
  USA: 'United States',
  UZB: 'Uzbekistan',
};

const TEAM_FLAGS = {
  ALG: '🇩🇿', ARG: '🇦🇷', AUS: '🇦🇺', AUT: '🇦🇹', BEL: '🇧🇪',
  BIH: '🇧🇦', BRA: '🇧🇷', CAN: '🇨🇦', CIV: '🇨🇮', COD: '🇨🇩',
  COL: '🇨🇴', CPV: '🇨🇻', CRO: '🇭🇷', CUW: '🇨🇼', CZE: '🇨🇿',
  ECU: '🇪🇨', EGY: '🇪🇬', ENG: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', ESP: '🇪🇸', FRA: '🇫🇷',
  GER: '🇩🇪', GHA: '🇬🇭', HAI: '🇭🇹', IRN: '🇮🇷', IRQ: '🇮🇶',
  JOR: '🇯🇴', JPN: '🇯🇵', KOR: '🇰🇷', KSA: '🇸🇦', MAR: '🇲🇦',
  MEX: '🇲🇽', NED: '🇳🇱', NOR: '🇳🇴', NZL: '🇳🇿', PAN: '🇵🇦',
  PAR: '🇵🇾', POR: '🇵🇹', QAT: '🇶🇦', RSA: '🇿🇦', SCO: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  SEN: '🇸🇳', SUI: '🇨🇭', SWE: '🇸🇪', TUN: '🇹🇳', TUR: '🇹🇷',
  URU: '🇺🇾', USA: '🇺🇸', UZB: '🇺🇿',
};

export function teamName(code) {
  return TEAM_NAMES[code] || code;
}

export function teamFlag(code) {
  return TEAM_FLAGS[code] || '';
}
